{
 "title": "Бизнес метрики",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Запросы отправленные дилеру",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "PayConsumerService_Consumed_TotalConsumed_total{application=\"payConsumerService\"}",
     "legendFormat": "Удачные"
    },
    {
     "expr": "PayConsumerService_Consumed_TotalFailed_total{application=\"payConsumerService\"}",
     "legendFormat": "Неудачные"
    }
   ]
  },
  {
   "title": "Среднее время запроса к дилеру",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "PayConsumerService_Consumed_Duration_seconds_sum{application=\"payConsumerService\"}/PayConsumerService_Consumed_Duration_seconds_count{application=\"payConsumerService\"}",
     "legendFormat": "Среднее время запроса"
    }
   ]
  },
  {
   "title": "Полученные дилером запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "PayDealerService_Dealed_TotalDealed_total",
     "legendFormat": "Полученные запросы"
    }
   ]
  }
 ]
}